

primary:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/place_qr_code?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: zxc,./123


secondary:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qr_record_service?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: zxc,./123

#  redis:
#    port: 6379
#    url: 120.79.189.55

#mybatis:
#  type-aliases-package: com.example.test2.POJO
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: false
#  security:
#    user:
#      name: admin
#      password: 123456

server:
  port: 8079
  servlet:
    context-path:

